#! /bin/bash
COUNTER=1
RADIOLIST=""  # variable where we will keep the list entries for radiolist dialog
for i in $HOME/.dotfiles/apps/*; do
    RADIOLIST="$RADIOLIST $COUNTER ${i##*/} off "
    let COUNTER=COUNTER+1
done

dialog --backtitle "Radiolist" \
--checklist "test" 0 0 $COUNTER \
$RADIOLIST