#!/bin/sh
UNAME=$( command -v uname)
case $( "${UNAME}" | tr '[:upper:]' '[:lower:]') in
  linux*)
    OSNAME='linux'
    ;;
  darwin*)
    OSNAME='darwin'
    ;;
  msys*|cygwin*|mingw*)
    # or possible 'bash on windows'
    OSNAME='windows'
    ;;
  nt|win*)
    OSNAME='windows'
    ;;
  *)
    OSNAME='unknown'
    ;;
esac

print $OSNAME;