#!/bin/bash

prompt_confirm() {
  while true; do
    read -r -n 1 -p "${1:-Continue?} [y/n]: " REPLY
    case $REPLY in
      [yY]) echo ; return 0 ;;
      [nN]) echo ; return 1 ;;
      *) printf " \033[31m %s \n\033[0m" "invalid input"
    esac 
  done  
}


if ! [ -x "$(command -v dialog)" ]; then
    # example usage
    prompt_confirm "Dialog is required, install it?" || exit 0
    echo -e "\e[42mInstalando Dialog... \e[0m"
    sudo apt update && sudo apt install dialog
    echo "dialog installed"
fi


if ! [ -x "$(command -v add-apt-repository)" ]; then
    prompt_confirm "software-properties-common is required, install it?" || exit 0
    sudo apt install software-properties-common
    echo "software-properties-common installed"
fi

if ! [ -x "$(command -v curl)" ]; then
    prompt_confirm "we require curl for some tasks, install it?" || exit 0
    sudo apt install software-properties-common
    echo "curl installed"
fi


cmd=(dialog --separate-output --checklist "Choose the : (recuerda actualizar primero con sudo apt update)" 22 76 16)
options=(1 "Elementary Tweaks (Elementary OS)" off    # puedes poner cualquier opción en "of" por defecto
    2 "Sublime Text 3" off
    3 "Git" off
    4 "ZSH" off
    5 "oh-my-zsh" off
    6 "oh-my-zsh plugins" off
    7 "Crear configuración" on
    8 "Vim y Plugins" off
    9 "LEMP" off
    10 "Composer" off
    11 "NVM" on
    12 "Spotify" off
    13 "Teamviewer" off
    14 "Inkscape" off
    15 "Flatpak" off
    16 "GIMP" off
    17 "VLC" off
    18 "Albert" off)

    choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
    clear

for choice in $choices
do
    case $choice in
        1)
            # Instalar elementary-tweaks
            echo -e "\e[42mInstalando elementary-tweaks... \e[0m"
            sudo add-apt-repository ppa:philip.scott/elementary-tweaks
            sudo apt install elementary-tweaks -y
            ;;
        2)
            # Instalar Sublime Text 3
            echo -e "\e[42mInstalando Sublime Text 3... \e[0m"
            wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
            sudo apt install apt-transport-https
            echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
            sudo apt update
            sudo apt install sublime-text -y
            ;;
        3)
            echo -e "\e[42mInstalando Git... \e[0m"
            sudo apt install git -y
            ;;
        4)
            echo -e "\e[42mInstalando ZSH... \e[0m"
            sudo apt install zsh -y
            ;;
        5)
            echo -e "\e[42mInstalando oh-my-zsh...\e[0m"
            sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
            ;;

        6)
            echo -e "\e[42mInstalando plugins de ZSH...\e[0m"
            # git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
            git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
            git clone https://github.com/zdharma/fast-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
            git clone https://github.com/rupa/z.git ~/z
            git clone https://github.com/djui/alias-tips.git ~/.oh-my-zsh/custom/plugins/alias-tips
            ;;
        7)
            echo -e "\e[42mConfiguración... \e[0m"
            echo -e "\e[33;1m Creando links y creando backups... \e[0m"
            # mv -iv ~/.gitconfig ~/.gitconfig.old
            if [ -x "$(command -v vim)" ]; then
                mv -iv $HOME/.vimrc $HOME/.vimrc-$RANDOM
                ln -sfnv "$HOME/.dotfiles/.vimrc" $HOME/.vimrc
                
            fi
            if [ -x "$(command -v zsh)" ]; then
                mv -iv $HOME/.zshrc $HOME/.zshrc-$RANDOM
                ln -sfnv "$HOME/.dotfiles/.zshrc" $HOME/.zshrc
                
            fi
            if [ -x "$(command -v tmux)" ]; then
                mv -iv $HOME/.tmux.conf $HOME/.tmux-$RANDOM.conf
                ln -sfnv "$HOME/.dotfiles/tmux/tmux.conf" $HOME/.tmux.conf
            fi
            # if [ -x "$(command -v alacritty)" ]; then
            #     if [ ! -d "$HOME/.config/alacritty" ]; then
            #         mkdir $HOME/.config/alacritty
            #     else
            #         mv -iv $HOME/.config/alacritty/alacritty.yml $HOME/.config/alacritty/alacritty-$RANDOM.yml
            #     fi
            #     ln -sfnv "$HOME/.dotfiles/config/alacritty/alacritty.yml" $HOME/.config/alacritty/alacritty.yml
                
            # fi
            if [ -x "$(command -v htop)" ]; then
                mv -iv ~/.config/htop/htoprc ~/.config/htop/htoprc-$RANDOM
                ln -sfnv "~/.dotfiles/config/htop/htoprc" ~/.config/htop/htoprc
            fi
            # ln -sfnv "$HOME/Dropbox/.gitconfig" ~/.gitconfig
            # if [ -x "$(command -v terminator)" ]; then
            #     mv -iv ~/.config/terminator/config ~/.config/terminator/config-$RANDOM
            #     ln -sfnv "~/.dotfiles/config/terminator/config" ~/.config/terminator/config
            #     continue
            # fi

            ;;
        8)
            echo -e "\e[42mInstalando plugins de vim... \e[0m"
            git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
            vim +PluginUpdate +qall
            ;;

        9)
            #Instalando LEMP stack
            echo -e "\e[42mInstalando NGINX... \e[0m"
            sudo apt install nginx -y
            
            echo "Instalando Mysql Server"
            sudo apt install mariadb-server -y

            echo "Instalando PHP"
            
            sudo add-apt-repository ppa:ondrej/php -y
            sudo apt install php-cli php-fpm php-zip php-curl php-xml php-json php-bcmath php-tokenizer php-mysql -y

            echo "Desactivando servicios"
            sudo systemctl disable nginx
            sudo systemctl disable mysql
            ;;
        10)
            echo -e "\e[42mInstalando Composer... \e[0m"
            echo -e "\e[36;1m Comparando firma y descargando Composer...\e[0m"
            EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

            if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
            then
                >&2 echo 'ERROR: Invalid installer signature'
                rm composer-setup.php
                exit 1
            fi
            echo -e "\e[36;1m Firma aprobada, instalando...\e[0m"
            php composer-setup.php --quiet
            RESULT=$?
            rm composer-setup.php
            sudo mv composer.phar /usr/bin/composer

            echo -e "\e[36;1m Composer instalado correctamente.\e[0m"
            composer --version
            echo $RESULT
            ;;

        11)
            echo -e "\e[42mInstalando NVM... \e[0m"
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            ;;
        12)
            echo -e "\e[42mInstalando spotify... \e[0m"
            curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add -  
            echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
            sudo apt update
            sudo apt install spotify-client -y
            ;;
        13)
            #Teamviewer
            echo -e "\e[42mInstalando teamviewer... \e[0m"
            wget -O Teamviewer.deb https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
            dpkg -i Teamviewer.deb
            sudo apt install -f -y
            rm -rf Teamviewer.deb
            ;;
        14)
            #Inkscape
            echo -e "\e[42mInstalando Inkscape... \e[0m"
            sudo add-apt-repository ppa:inkscape.dev/stable -y
            sudo apt update
            sudo apt install inkscape -y
            ;;
        15)
            #Flatpak
            echo -e "\e[42mInstalando Flatpak... \e[0m"
            sudo apt install flatpak
            flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
            echo -e "\e[42mYou should restart your computer before installing flatpak apps\e[0m"
            ;;
        16)
            #Gimp
            if ! [ -x "$(command -v flatpak)" ]; then
                echo -e "\e[101mPara instalar GIMP necesitas tener \e[42;1mflatpak\e[101m instaldo\e[0m"
            else
                echo -e "\e[42mInstalando GIMP... \e[0m"
                flatpak install flathub org.gimp.GIMP -y
            fi
            ;;
        17)
            #vlc
            echo -e "\e[42m Instalando VLC... \e[0m"
            sudo apt install vlc -y
            ;;
        18)
            #Albert
            echo -e "\e[40m Se instaló Albert \e[0m ✔️"
            echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.04/ /' | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list
            curl -fsSL https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_18.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home:manuelschneid3r.gpg > /dev/null
            sudo apt update
            sudo apt install albert -y
            ;;
    esac
done
