#!/bin/bash

# check if parameter is -v or --version
if [[ $1 == "-v" || $1 == "--version" ]]; then
    echo "t version 0.1"
    exit 0
fi

# Credit to ThePrimeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=`find ~/Dev -maxdepth 1 -mindepth 1 -type d`
    items+=`echo -e "\n/tmp"`
    selected=`echo "$items" | fzf`
fi

dirname=`basename $selected | sed 's/\./_/g'`

tmux switch-client -t =$dirname
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname
