POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status dir_writable dir vcs )
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( root_indicator background_jobs)

 POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\uE0C6'
 POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\uE0C7'

#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
#POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_USER_ICON="\uF415" # 
POWERLEVEL9K_ROOT_ICON="\uF09C"
#POWERLEVEL9K_SUDO_ICON=$'\uF09C' # 
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_VCS_GIT_ICON='\uF408 '
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uF408 '

#Colour
POWERLEVEL9K_COLOR_SCHEME="dark"
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="yellow"
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="black"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="green"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="purple"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND="purple"
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="red"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND="red"
POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND="red"
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND="black"

POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="025"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="032"


POWERLEVEL9K_DIR_ETC_BACKGROUND="red"

POWERLEVEL9K_DIR_HOME_BACKGROUND="025"
POWERLEVEL9K_DIR_HOME_FOREGROUND="032"


POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="025"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="032"


POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND="red"
POWERLEVEL9K_HISTORY_BACKGROUND="green"
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="green"
POWERLEVEL9K_LOAD_WARNING_BACKGROUND="yellow"

POWERLEVEL9K_OS_ICON_BACKGROUND="025"
POWERLEVEL9K_OS_ICON_FOREGROUND="darkcyan"

POWERLEVEL9K_RAM_BACKGROUND="yellow"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="red"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="black"

POWERLEVEL9K_STATUS_OK_BACKGROUND="016"
POWERLEVEL9K_STATUS_OK_FOREGROUND="154"

POWERLEVEL9K_TIME_BACKGROUND="darkcyan"

POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND="025"
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND="032"

POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND="black"
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND="white"

    POWERLEVEL9K_VCS_CLEAN_BACKGROUND="022"
    POWERLEVEL9K_VCS_CLEAN_FOREGROUND="048"

    POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="009"
    POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="255"

    POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="226"
    POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="234"

    POWERLEVEL9K_VCS_CLOBBERED_BACKGROUND="001"
    POWERLEVEL9K_VCS_CLOBBERED_FOREGROUND="234"


    
    
    